pretrained_model_name: microsoft/deberta-base
max_seq_length: 384
classifier_hidden_sizes:
  - 448
  - 256
dropout: 0.21495447160923437
loss_type: adaptive_focal
alpha: 0.25
gamma: 2.0
delta: 1.0
use_gradient_checkpointing: true
