defaults:
  - data: default
  - model: roberta_base
  - training: default
  - hpo: default
  - _self_

seed: 1337

mlflow:
  tracking_uri: ${env:MLFLOW_TRACKING_URI, "http://127.0.0.1:5000"}
  experiment_name: ${env:MLFLOW_EXPERIMENT_NAME, "redsm5_classification"}
  nested: false
  autolog: true

hydra:
  run:
    dir: outputs/${model.encoder.type}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
