name: redsm5
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - -r requirements.txt
variables:
  MLFLOW_TRACKING_URI: http://host.docker.internal:5500
  PYTHONDONTWRITEBYTECODE: "1"
  WANDB_MODE: disabled
  # CPU threading optimization for i7-8700 (6 cores)
  OMP_NUM_THREADS: "6"
  MKL_NUM_THREADS: "6"
  OPENBLAS_NUM_THREADS: "6"
