batch_size: 32
grad_accum: 2
epochs: 500
lr: 2.0e-5
weight_decay: 0.01
warmup_ratio: 0.06
fp16: true
bf16: false
gradient_checkpointing: true
dataloader_pin_memory: true
dataloader_num_workers: 6
eval_every_steps: 500
save_k_best: 2
early_stop_patience: 5
max_grad_norm: 1.0
